SELECT A.TITLE, B.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, B.CREATED_DATE
FROM USED_GOODS_BOARD AS A
INNER JOIN USED_GOODS_REPLY AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.CREATED_DATE >= '2022-10-01' and A.CREATED_DATE < '2022-11-01'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;